baseURL: "https://akers.kz/"
languageCode: "ru"
title: "АКЕРС-СТОМ"
copyright: "ТОО \"АКЕРС-СТОМ\""
paginate: 6
params:
  author: "SYSTEMD"
  description: "Медицинское оборудование и комплектующие"
  sections:
    hero:
      title: "АКЕРС-СТОМ"
      header: "Наши партнеры:"
      lead: "Медицинское оборудование и комплектующие."
    blog:
      title: "Новости и акции"
      header: "Новости и акции"
      lead: "Новости и акции"
    contact:
      title: "Наши контакты"
      lead: "Свяжитесь с нами удобным для Вас способом"
      phone: "+7 (727) 279 84 35"
      mobile: "+7 (700) 978 45 60"
      fax: "+7 (727) 279 84 46"
      email: "akdiplomat@bk.ru"
      address: "пр. СЕЙФУЛЛИНА 434, угол ул. ЖИБЕК ЖОЛЫ, оф. 105"
menu:
  main:
  - identifier: about
    name: О нас
    title: О нас
    url: /about/
    weight: -200
  - identifier: blog
    name: Новости и акции
    title: Новости и акции
    url: /blog/
    weight: -190
  - identifier: product
    name: Продукция
    title: Продукция
    url: /product/
    weight: -180
  - identifier: endoscopic
    name: Эндоскопическое Оборудование
    title: Эндоскопическое Оборудование
    url: /product/endoscopic/
    parent: product
    weight: -170
  - identifier: urology
    name: Урология
    title: Урология
    url: /product/endoscopic/urology/
    parent: endoscopic
    weight: -169
  - identifier: gynecology
    name: Гинекология
    title: Гинекология
    url: /product/endoscopic/gynecology/
    parent: endoscopic
    weight: -168
  - identifier: surgery
    name: Хирургия
    title: Хирургия
    url: /product/endoscopic/surgery/
    parent: endoscopic
    weight: -167
  - identifier: spine_surgery
    name: Хирургия позвоночника
    title: Хирургия позвоночника
    url: /product/endoscopic/spine_surgery/
    parent: endoscopic
    weight: -166
  - identifier: proctology
    name: Проктология
    title: Проктология
    url: /product/endoscopic/proctology/
    parent: endoscopic
    weight: -165
  - identifier: visualization
    name: Визуализация
    title: Визуализация
    url: /product/endoscopic/visualization/
    parent: endoscopic
    weight: -164
  - identifier: ent
    name: Оборудование и инструменты для лор
    title: Оборудование и инструменты для лор
    url: /product/endoscopic/ent/
    parent: endoscopic
    weight: -163
  - identifier: thoracoscopy
    name: Торакоскопия
    title: Торакоскопия
    url: /product/endoscopic/thoracoscopy/
    parent: endoscopic
    weight: -162
  - identifier: arthroscopy
    name: Артроскопическое оборудование
    title: Артроскопическое оборудование
    url: /product/endoscopic/arthroscopy/
    parent: endoscopic
    weight: -161
  - identifier: core
    name: Интеграционная операционная система (CORE)
    title: Интеграционная операционная система (CORE)
    url: /product/endoscopic/core/
    parent: endoscopic
    weight: -160
  - identifier: stom
    name: Стоматологические установки
    title: Стоматологические установки
    url: /product/stom/
    parent: product
    weight: -159
  - identifier: diplomat
    name: Дипломат (Словакия)
    title: Дипломат (Словакия)
    url: /product/stom/diplomat/
    parent: stom
    weight: -158
  - identifier: zc
    name: ZC-9400A (Китай)
    title: ZC-9400A (Китай)
    url: /product/stom/zc/
    parent: stom
    weight: -157
  - identifier: tipsandmicromotors
    name: Наконечники, Микромоторы
    title: Наконечники, Микромоторы
    url: /product/tipsandmicromotors/
    parent: product
    weight: -150
  - identifier: turbo
    name: Турбинные наконечники
    title: Турбинные наконечники
    url: /product/tipsandmicromotors/turbo/
    parent: tipsandmicromotors
    weight: -149
  - identifier: angularandstraight
    name: Угловые и прямые наконечники
    title: Угловые и прямые наконечники
    url: /product/tipsandmicromotors/angularandstraight/
    parent: tipsandmicromotors
    weight: -148
  - identifier: micromotors
    name: Микромоторы
    title: Микромоторы
    url: /product/tipsandmicromotors/micromotors/
    parent: tipsandmicromotors
    weight: -147
  - identifier: maxillofacial
    name: Челюстно лицевая хирургия и имплантология
    title: Челюстно лицевая хирургия и имплантология
    url: /product/tipsandmicromotors/maxillofacial/
    parent: tipsandmicromotors
    weight: -146
  - identifier: care
    name: Средства по уходу
    title: Средства по уходу
    url: /product/tipsandmicromotors/care/
    parent: tipsandmicromotors
    weight: -145
  - identifier: compressor
    name: Компрессоры
    title: Компрессоры
    url: /product/compressor/
    parent: product
    weight: -140
  - identifier: ekom-compressor
    name: Компрессоры EKOM
    title: Компрессоры EKOM
    url: /product/compressor/ekom/
    parent: compressor
    weight: -139
  - identifier: diplomat-compressor
    name: Компрессоры Дипломат
    title: Компрессоры Дипломат
    url: /product/compressor/diplomat/
    parent: compressor
    weight: -138
  - identifier: china-compressor
    name: Компрессоры Китай
    title: Компрессоры Китай
    url: /product/compressor/china/
    parent: compressor
    weight: -137
  - identifier: disinfection
    name: Дезинфекция, Стерилизация
    title: Дезинфекция, Стерилизация
    url: /product/disinfection/
    parent: product
    weight: -130
  - identifier: autoclaves
    name: Автоклавы
    title: Автоклавы
    url: /product/disinfection/autoclaves/
    parent: disinfection
    weight: -129
  - identifier: washing
    name: Моечные машины
    title: Моечные машины
    url: /product/disinfection/washing/
    parent: disinfection
    weight: -128
  - identifier: packing
    name: Упаковочные машины
    title: Упаковочные машины
    url: /product/disinfection/packing/
    parent: disinfection
    weight: -127
  - identifier: store
    name: Камера хранения стерильных инструментов
    title: Камера хранения стерильных инструментов
    url: /product/disinfection/store/
    parent: disinfection
    weight: -126
  - identifier: recirculator
    name: Рециркуляторы
    title: Рециркуляторы
    url: /product/disinfection/recirculator/
    parent: disinfection
    weight: -125
  - identifier: distiller
    name: Дистиллятор
    title: Дистиллятор
    url: /product/disinfection/distiller/
    parent: disinfection
    weight: -124
  - identifier: xray
    name: Рентген оборудование
    title: Рентген оборудование
    url: /product/disinfection/xray/
    parent: product
    weight: -110
  - identifier: sighting
    name: Прицельные
    title: Прицельные
    url: /product/xray/sighting/
    parent: xray
    weight: -109
  - identifier: 2d
    name: 2D диагностика
    title: 2D диагностика
    url: /product/xray/2d/
    parent: xray
    weight: -108
  - identifier: 3d
    name: 3D диагностика
    title: 3D диагностика
    url: /product/xray/3d/
    parent: xray
    weight: -107
  - identifier: intraoral
    name: Интраоральная диагностика
    title: Интраоральная диагностика
    url: /product/xray/intraoral/
    parent: xray
    weight: -106
  - identifier: protection
    name: Рентгензащитная одежда
    title: Рентгензащитная одежда
    url: /product/xray/protection/
    parent: xray
    weight: -105
  - identifier: stomfurniture
    name: Стоматологическая мебель
    title: Стоматологическая мебель
    url: /product/stomfurniture/
    parent: product
    weight: -80
  - identifier: instruments
    name: Стоматологические инструменты
    title: Стоматологические инструменты
    url: /product/instruments/
    parent: product
    weight: -70
  - identifier: removal
    name: Удаления
    title: Удаления
    url: /product/instruments/removal/
    parent: instruments
    weight: -69
  - identifier: implantation
    name: Хирургия и имплантация
    title: Хирургия и имплантация
    url: /product/instruments/implantation/
    parent: instruments
    weight: -68
  - identifier: diagnostics
    name: Диагностика
    title: Диагностика
    url: /product/instruments/diagnostics/
    parent: instruments
    weight: -67
  - identifier: restoration
    name: Терапевтическая реставрация
    title: Терапевтическая реставрация
    url: /product/instruments/restoration/
    parent: instruments
    weight: -66
  - identifier: endodontics
    name: Эндодонтия
    title: Эндодонтия
    url: /product/instruments/endodontics/
    parent: instruments
    weight: -65
  - identifier: periodontal
    name: Пародонтологическое
    title: Пародонтологическое
    url: /product/instruments/periodontal/
    parent: instruments
    weight: -64
  - identifier: spoons
    name: Оттискные ложки
    title: Оттискные ложки
    url: /product/instruments/spoons/
    parent: instruments
    weight: -63
  - identifier: laboratory
    name: Лаборатория
    title: Лаборатория
    url: /product/instruments/laboratory/
    parent: instruments
    weight: -62
  - identifier: orthodontics
    name: Ортодонтия
    title: Ортодонтия
    url: /product/instruments/orthodontics/
    parent: instruments
    weight: -61
  - identifier: parts
    name: Запасные части
    title: Запасные части
    url: /product/parts/
    parent: product
    weight: -50
  - identifier: parts-diplomat
    name: з/ч дипломат
    title: з/ч дипломат
    url: /product/parts/diplomat/
    parent: parts
    weight: -49
  - identifier: parts-china
    name: з/ч китай
    title: з/ч китай
    url: /product/parts/china/
    parent: parts
    weight: -48
  - identifier: parts-ekom
    name: з/ч компрессоры ECOM
    title: з/ч компрессоры ECOM
    url: /product/parts/ekom/
    parent: parts
    weight: -47
  - identifier: parts-bienair
    name: з/ч инструменты (BienAir)
    title: з/ч инструменты (BienAir)
    url: /product/parts/bienair/
    parent: parts
    weight: -46
  - identifier: extra
    name: Дополнительное оборудование
    title: Дополнительное оборудование
    url: /product/extra/
    parent: product
    weight: -30
  - identifier: lab
    name: Зуботехническая Лаборатория
    title: Зуботехническая Лаборатория
    url: /product/lab/
    parent: product
    weight: -20
  - identifier: milling
    name: Фрезерный аппарат
    title: Фрезерный аппарат
    url: /product/lab/milling/
    parent: lab
    weight: -19
  - identifier: foundry
    name: Литейный аппарат
    title: Литейная аппарат
    url: /product/lab/foundry/
    parent: lab
    weight: -18
  - identifier: vacuum
    name: Вакуум-формировочная машина
    title: Вакуум-формировочная машина
    url: /product/lab/vacuum/
    parent: lab
    weight: -17
  - identifier: gallery
    name: Галерея
    title: Галерея
    url: /gallery/
    weight: -10
